# Generated by Django 5.1.1 on 2026-09-13 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shared home', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HolidayIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('destination', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('places', models.TextField(blank=True)),
                ('activities', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('suggested_by', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('planning', 'Planning'), ('booked', 'Booked')], default='idea', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_ideas', to='household.household')),
            ],
        ),
        migrations.CreateModel(
            name='DinnerIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinner_ideas', to='household.household')),
            ],
        ),
        migrations.CreateModel(
            name='DateIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('suggested_by', models.CharField(blank=True, max_length=80)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('approx_cost', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('planned', 'Planned'), ('done', 'Done')], default='idea', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_ideas', to='household.household')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('icon', models.CharField(blank=True, max_length=20)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='household.household')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('household', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('holiday', 'Holiday'), ('recipe', 'Recipe'), ('place', 'Place'), ('other', 'Other')], default='other', max_length=20)),
                ('url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='household.household')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('owner_type', models.CharField(choices=[('unassigned', 'Unassigned'), ('either', 'Either'), ('assigned', 'Assigned')], default='unassigned', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('effort', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('recurrence', models.CharField(choices=[('none', 'No recurrence'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='none', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='household.category')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='household.household')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('completed', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='household.task')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(choices=[('wisteria', 'Wisteria'), ('sage', 'Sage'), ('sky', 'Sky'), ('peach', 'Peach'), ('butter', 'Butter'), ('coral', 'Coral'), ('slate', 'Slate')], default='wisteria', max_length=20)),
                ('avatar', models.CharField(blank=True, default='A', max_length=2)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='household.household')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='household_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('kind', models.CharField(choices=[('film', 'Film'), ('tv', 'TV')], default='film', max_length=20)),
                ('genre', models.CharField(blank=True, max_length=80)),
                ('recommended_by', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('want', 'Want to watch'), ('watching', 'Watching'), ('watched', 'Watched')], default='want', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_items', to='household.household')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_calendar_id', models.CharField(blank=True, max_length=200)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_integrations', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_integrations', to='household.household')),
            ],
            options={
                'unique_together': {('household', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('dinner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_entries', to='household.dinneridea')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan', to='household.household')),
            ],
            options={
                'unique_together': {('household', 'day')},
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_due', models.BooleanField(default=True)),
                ('shopping_updates', models.BooleanField(default=True)),
                ('partner_claimed_task', models.BooleanField(default=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='household.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('household', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('list_type', models.CharField(choices=[('groceries', 'Groceries'), ('other', 'Other shopping')], default='groceries', max_length=20)),
                ('section', models.CharField(blank=True, max_length=80)),
                ('note', models.CharField(blank=True, max_length=260)),
                ('checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='household.household')),
            ],
            options={
                'ordering': ['-checked', 'section', 'name'],
                'indexes': [models.Index(fields=['household', 'list_type', 'checked'], name='household_s_househo_6fc27e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['household', 'due_date'], name='household_t_househo_4896c4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner', 'due_date'], name='household_t_owner_i_19e981_idx'),
        ),
    ]
