# Generated by Django 5.1.1 on 2026-09-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['priority', '-created_at']},
        ),
    ]
